version: "3.4"
services:
  inserter:
    image: inserter:latest
    build:
      context: ./microservice/
      dockerfile: ./Dockerfile
    depends_on:
      - db
    networks:
      - dockerCoaching
    environment:
      MONGODB_CONNSTRING: mongodb://admin:admin@db
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        order: start-first

  db:
    image: mongo:4
    networks:
      - dockerCoaching
    volumes:
      - ./data/:/data/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_USER_PW}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        order: start-first
  
  db-gui:
    image: mongo-express:latest
    depends_on:
      - db
    networks:
      - dockerCoaching
    ports:
      - ${DB_GUI_PORT:-9000}:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_GUI_USER_NAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_GUI_USER_PW}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_ROOT_USER_NAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_ROOT_USER_PW}
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_PORT: 27017
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        order: start-first

networks:
  dockerCoaching: